<a href="https://colab.research.google.com/github/yongjun1994/branchTest/blob/main/9_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%ED%94%84%EB%A0%88%EC%9E%84%EC%9B%8C%ED%81%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 파이토치
PyTorch는 파이썬 기반의 오픈소스 딥러닝 프레임워크로, 파이썬 코드로 AI 모델을 직관적으로 만들고 학습할 수 있도록 도와주는 도구입니다. 특히 동적 계산 그래프 방식을 사용하기 때문에 코드 실행 시점에 실시간으로 계산 흐름이 결정되어 디버깅과 수정이 쉽고, GPU 가속과 자동 미분 기능을 통해 대규모 모델도 빠르게 학습할 수 있습니다.

> 동적 계산 그래프 방식은

> 딥러닝 모델이 학습 및 예측을 수행할 때 계산 그래프를 실행 시점(runtime)에 실시간으로 생성 및 수정하는 방식입니다. 이 방식은 조건문, 반복문 등 복잡한 논리 구조를 유연하게 처리할 수 있으며, 주로 PyTorch와 같은 프레임워크에서 사용됩니다. 계산 그래프는 입력 데이터를 바탕으로 연산을 수행하면서 그래프를 생성하고, 역전파를 통해 미분을 계산하며, 최종적으로 가중치를 업데이트하는 과정을 거칩니다. 이러한 특성 덕분에 디버깅이 용이하고 연구 및 개발 속도가 빠르며 직관적인 코드 작성이 가능합니다.

### 1-1. 스칼라
스칼라(Scalar)는 단 하나의 숫자(정수, 실수 등)만을 담는 자료형을 말합니다. 파이토치(PyTorch)에서 스칼라는 0차원 텐서(0-dimensional Tensor)로 표현합니다. 즉, 텐서의 차원(Shape)이 전혀 없는 상태를 의미합니다.

In [ ]:
!pip install torch

In [ ]:
import torch

In [ ]:
var1 = torch.tensor(5) # torch의 tensor라는 자료구조에 5를 저장
print(var1)
print(var1.shape) # 0차원 텐서
var2 = torch.tensor([10])
print(var2.shape) # 1차원 텐서 -> 스칼라가 아님

var3 = torch.tensor(3)
# result = var1 + var2
result = var1 + var3
print(result)
print(result.item()) # 텐서의 값(스칼라)을 파이썬 숫자로 추출

tensor(5)
torch.Size([])
torch.Size([1])
tensor(8)
8


### 1-2. 벡터(Vector)
벡터(Vector)는 하나 이상의 원소가 일렬로 나열된 1차원 텐서(1D Tensor)를 의미합니다. 파이토치(PyTorch)에서 벡터는 일반적으로 torch.tensor([...]) 형태로 만들며, 이때 텐서의 shape(차원)가 (n,) 형태입니다. 즉, 원소가 n개 들어 있으면 1차원 벡터가 됩니다.

In [ ]:
var1 = torch.tensor([1.0, 2.0, 3.0])
print(var1)
print(var1.shape) # 1차원 텐서

var2 = var1 + 10
print(var2)
var3 = var1 * 2
print(var3)
var4 = torch.tensor([4.0, 5.0, 6.0])
result = var1 + var4
print(result)

tensor([1., 2., 3.])
torch.Size([3])
tensor([11., 12., 13.])
tensor([2., 4., 6.])
tensor([5., 7., 9.])


### 1-3. 행렬
행렬(Matrix)은 2차원 형태의 텐서로, 파이토치(PyTorch)에서는 shape가 (m, n)처럼 2개의 차원을 가진 텐서를 의미합니다. 예를 들어, torch.tensor([[1, 2], [3, 4]])는 2행×2열 형태의 행렬입니다. 행렬 연산에서는 행렬 곱셈, 원소별 연산, 전치(Transpose) 등이 자주 활용되며, 파이토치는 torch.mm 또는 @ 연산자를 통해 행렬 곱셈을 수행할 수 있습니다.

In [ ]:
var1 = torch.tensor([[1, 2], [3, 4]])
var2 = torch.tensor([[5, 6], [7, 8]])
print(var1)
print(var1.shape) # 2차원 텐서

result1 = var1 + var2
print(result1)
result2 = var1 + var2
print(result2)
result3 = torch.mm(var1, var2)
print(result3)
result4 = var1 @ var2 # @은 행렬곱에 사용할 수 있는 연산자
print(result4)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
tensor([[ 6,  8],
        [10, 12]])
tensor([[ 6,  8],
        [10, 12]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


### 1-4. 다차원 텐서
파이토치(PyTorch)에서 다차원 텐서란, 여러 축(차원)을 가지는 텐서를 의미합니다. 예를 들어, 0차원 텐서는 “스칼라(Scalar)”, 1차원 텐서는 “벡터(Vector)”, 2차원 텐서는 “행렬(Matrix)”, 그 이상의 3차원, 4차원 텐서 등을 통틀어 “다차원 텐서(Multi-dimensional Tensor)”라고 부릅니다. 다차원 텐서는 이미지, 음성, 동영상, 시계열 데이터를 비롯하여 여러 축을 필요로 하는 다양한 형태의 데이터를 표현할 때 쓰입니다.

In [ ]:
var1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(var1)
print(var1.shape) # torch.Size([2, 2, 2]) : 2행 2열이 2개있다.

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


<img src ='https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2F9qUBb%2FbtsLwdzdXkJ%2Fx1zeP2l6zS8o5sMjOIr5Ek%2Fimg.png'>

# 2. 텐서
PyTorch의 텐서(Tensor)는 딥러닝 모델에서 데이터를 다룰 때 사용되는 기본 데이터 구조입니다. 텐서는 다차원 배열로, NumPy의 배열과 비슷하지만, GPU에서 연산을 수행할 수 있다는 점에서 차이가 있습니다. PyTorch의 텐서는 데이터의 표현뿐만 아니라, 자동 미분(autograd) 기능을 제공하여 딥러닝 모델의 학습을 도와줍니다.

In [ ]:
data = [[1, 2], [3, 4]]
t1 = torch.tensor(data)
print(t1)

tensor([[1, 2],
        [3, 4]])


In [ ]:
# t1, t2에 텐서형으로 저장
t1 = torch.tensor([5])
t2 = torch.tensor([7])

ndarr1 = (t1 + t2).numpy()
print(ndarr1)
print(type(ndarr1))

result = ndarr1 * 10
t3 = torch.from_numpy(result)
print(t3)
print(type(t3))

[12]
<class 'numpy.ndarray'>
tensor([120])
<class 'torch.Tensor'>


In [ ]:
# 2차원 데이터를 갖고 있는 행렬
t1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(t1[0])
print(t1[:, 0])
print(t1[:, -1])
print(t1[..., -1])

tensor([1, 2, 3, 4])
tensor([1, 5, 9])
tensor([ 4,  8, 12])
tensor([ 4,  8, 12])


In [ ]:
# 3차원 이상
t1 = torch.tensor([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(t1)
print(t1.shape)
print(t1[..., -1]) # 첫 번째와 두 번째 차원을 유지. 마지막 요소만 선택

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3])
tensor([[ 3,  6],
        [ 9, 12]])


# 3. GPU 사용하기
GPU (Graphics Processing Unit)는 그래픽 처리 장치로, 주로 이미지 렌더링과 같은 대규모 병렬 계산을 수행하는 데 최적화된 하드웨어입니다. 원래는 그래픽 처리를 위해 설계되었지만, 최근에는 인공지능(AI) 및 딥러닝의 연산 가속기로 널리 사용되고 있습니다. 딥러닝은 수천, 수만 개의 행렬 및 벡터 연산을 필요로 합니다. GPU는 여러 개의 코어를 사용하여 이 연산을 병렬로 처리할 수 있습니다. 따라서 GPU는 딥러닝 에 최적화된 구조를 가지고 있습니다.

In [ ]:
data = [[1, 2], [3, 4]]
t1 = torch.tensor(data)
print(t1.is_cuda) # False : GPU를 못씀

False


In [ ]:
t1 = t1.cuda() # 텐서를 GPU로 옮기기

In [ ]:
print(t1.is_cuda)

True


In [ ]:
t1 = t1.cpu() # 텐서를 CPU로 옮기기
print(t1.is_cuda)

False


In [ ]:
t1 = torch.tensor([[1, 1], [2, 2]]).cuda()
t2 = torch.tensor([[5, 6], [7, 8]])

In [ ]:
# print(torch.matmul(t1, t2)) # 같은 디바이스에 있어야 함. 오류 발생
print(torch.matmul(t1.cpu(), t2)) # t1 = t1.cpu()
print(f'Device: {t1.device}')
print(f'Device: {t2.device}')

tensor([[12, 14],
        [24, 28]])
Device: cuda:0
Device: cpu


# 4. 텐서의 연산과 함수

In [ ]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])
t2 = torch.tensor([
    [5, 6],
    [7, 8]
])
print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [ ]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])
t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

print(t1.matmul(t2))
print(torch.matmul(t1, t2))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [ ]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(t1)
print(t1.mean()) # 전체 요소에 대한 평균
print(t1.mean(dim=0)) # 각 열에 대하여 평균 계산
print(t1.mean(dim=1)) # 각 행에 대하여 평균 계산

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(4.5000)
tensor([3., 4., 5., 6.])
tensor([2.5000, 6.5000])


In [ ]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(t1)
print(t1.sum()) # 전체 합계
print(t1.sum(dim=0)) # 각 열에 대하여 합계 계산
print(t1.sum(dim=1)) # 각 행에 대하여 합계 계산

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(36.)
tensor([ 6.,  8., 10., 12.])
tensor([10., 26.])


In [ ]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(t1)
print(t1.argmax()) # 전체 원소에 대한 최댓값의 인덱스를 구함
print(t1.argmax(dim=0)) # 각 열에 대하여 최댓값의 인덱스
print(t1.argmax(dim=1)) # 각 행에 대하여 최댓값의 인덱스

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(7)
tensor([1, 1, 1, 1])
tensor([3, 3])


# 5. 텐서의 차원 조작

In [ ]:
t1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [ ]:
result = torch.cat([t1, t1, t1], dim=0) # 행을 기준으로 이어 붙이기
print(result)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [ ]:
result = torch.cat([t1, t1, t1], dim=1) # 열을 기준으로 이어 붙이기
print(result)

tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])


In [ ]:
t1 = torch.tensor([2], dtype=torch.int)
t2 = torch.tensor([5.0])

print(t1.dtype)
print(t2.dtype)

torch.int32
torch.float32


In [ ]:
print(t1 + t2) # 큰 데이터 타입쪽으로 변환, float로 자동 형변환

tensor([7.])


In [ ]:
print(t1 + t2.type(torch.int32))

tensor([7], dtype=torch.int32)


In [ ]:
# view(): 텐서의 모양을 변경할 때 사용
t1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
t2 = t1.view(4, 2) # 4행2열로 저장
t2

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [ ]:
t1[0] = 7
print(t1)
print(t2)

tensor([7, 2, 3, 4, 5, 6, 7, 8])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
t3 = t1.clone().view(4, 2)
t1[0] = 9
print(t1)
print(t2)
print(t3)

tensor([9, 2, 3, 4, 5, 6, 7, 8])
tensor([[9, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
t1 = torch.rand((64, 32, 3)) # 32행 3열을 64개를 만들어라
print(t1.shape)

# permute : 인덱스를 활용하여 차원의 순서를 교환
t2 = t1.permute(2, 1, 0)
print(t2.shape)

torch.Size([64, 32, 3])
torch.Size([3, 32, 64])


In [ ]:
t1

tensor([[[4.0066e-04, 9.3163e-01, 6.1637e-02],
         [9.9556e-01, 1.5255e-01, 3.0869e-01],
         [5.5935e-01, 6.3908e-01, 7.1507e-01],
         ...,
         [2.1692e-01, 5.2766e-01, 2.4876e-02],
         [4.8752e-01, 4.4527e-01, 3.7202e-01],
         [6.8773e-01, 6.8458e-01, 8.2421e-01]],

        [[2.7179e-01, 6.3639e-01, 6.1296e-01],
         [9.9926e-01, 9.3552e-01, 2.4540e-01],
         [1.2099e-01, 5.2234e-01, 9.6133e-02],
         ...,
         [1.4781e-01, 8.4433e-01, 8.8164e-01],
         [8.3951e-01, 8.1548e-01, 1.3895e-01],
         [3.4806e-01, 4.9638e-02, 1.7329e-01]],

        [[9.4195e-01, 1.1931e-01, 1.4770e-01],
         [4.7681e-01, 8.6638e-02, 5.7690e-01],
         [8.3990e-01, 3.3952e-01, 9.1464e-01],
         ...,
         [1.0918e-01, 5.3828e-01, 5.5174e-01],
         [2.8991e-03, 5.0982e-01, 4.4481e-01],
         [5.9123e-01, 5.5496e-01, 7.0001e-01]],

        ...,

        [[2.4709e-01, 6.4227e-01, 9.1203e-01],
         [2.6830e-01, 8.1049e-01, 7.8415e-01]

In [ ]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(t1.shape) # 2행4열

# 첫번째 축에 차원 추가
t1 = t1.unsqueeze(0)
print(t1)
print(t1.shape)

torch.Size([2, 4])
tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
torch.Size([1, 2, 4])


In [ ]:
# 크기가 1인 차원을 제거함. squeeze(dim): 특정 차원이 1인 경우에만 차원을 제거
t1 = t1.squeeze()
print(t1)
print(t1.shape)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])


# 6. 자동 미분과 기울기

In [ ]:
x = torch.tensor([3.0, 4.0], requires_grad=True)
y = torch.tensor([1.0, 2.0], requires_grad=True)

In [ ]:
z = x + y
z

tensor([4., 6.], grad_fn=<AddBackward0>)

In [ ]:
out = z.mean()
out

tensor(5., grad_fn=<MeanBackward0>)

In [ ]:
out.backward() # 역전파 : 내가 지금까지 썼던 수식을 반대로 미분함

In [ ]:
print('x.grad: ', x.grad)
print('y.grad: ', y.grad)
print('z.grad: ', z.grad)

x.grad:  tensor([0.5000, 0.5000])
y.grad:  tensor([0.5000, 0.5000])
z.grad:  None


<ipython-input-52-38d263e1bb4c>:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  print('z.grad: ', z.grad)
